__title__ = "openxdf"
__description__ = "OpenXDF is a Python module built for interacting with Open eXchange Data Format files."
__url__ = "https://github.com/opelr/openxdf"
__version__ = "0.4.4"
__author__ = "Ryan Opel"
__author_email__ = "ryan.a.opel@gmail.com"
__license__ = "Apache 2.0"
__copyright__ = "Copyright 2018 Ryan Opel"
